# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV DATABASE_URL ""
ENV SECRET_KEY ""
ENV ACCESS_TOKEN_EXPIRE_MINUTES ""
ENV CELERY_BROKER_URL ""
# Run app.py when the conta

# Run app.py when the container launches
CMD ["celery", "--app", "celery_app.tasks", "worker", "--loglevel=info", "--concurrency=4", "--pool=solo"]